CREATE TABLE IF NOT EXISTS chats (
  id TEXT PRIMARY KEY,
  client_key TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT 'New Chat',
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK(role IN ('user','assistant')),
  content TEXT NOT NULL,
  page_images TEXT,
  artifact_html TEXT,
  checklist TEXT,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS rate_limit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_key TEXT NOT NULL,
  timestamp BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chats_client_updated
ON chats(client_key, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_chat_created
ON messages(chat_id, created_at ASC);

CREATE INDEX IF NOT EXISTS idx_rate_limit_key_time
ON rate_limit(client_key, timestamp);
