import { neon } from '@neondatabase/serverless'

type SqlClient = ReturnType<typeof neon>

let sqlClient: SqlClient | null = null
let schemaPromise: Promise<void> | null = null

export function getSql(): SqlClient {
  const databaseUrl = process.env.DATABASE_URL
  if (!databaseUrl) {
    throw new Error('DATABASE_URL is required. Add your Neon pooled connection string to .env or Vercel env vars.')
  }

  if (!sqlClient) {
    sqlClient = neon(databaseUrl)
  }

  return sqlClient
}

async function createSchema(sql: SqlClient): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS chats (
      id TEXT PRIMARY KEY,
      client_key TEXT NOT NULL,
      title TEXT NOT NULL DEFAULT 'New Chat',
      created_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL
    )
  `

  await sql`
    CREATE TABLE IF NOT EXISTS messages (
      id TEXT PRIMARY KEY,
      chat_id TEXT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
      role TEXT NOT NULL CHECK(role IN ('user','assistant')),
      content TEXT NOT NULL,
      page_images TEXT,
      artifact_html TEXT,
      checklist TEXT,
      created_at BIGINT NOT NULL
    )
  `

  await sql`
    CREATE TABLE IF NOT EXISTS rate_limit (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      client_key TEXT NOT NULL,
      timestamp BIGINT NOT NULL
    )
  `

  await sql`
    CREATE INDEX IF NOT EXISTS idx_chats_client_updated
    ON chats(client_key, updated_at DESC)
  `

  await sql`
    CREATE INDEX IF NOT EXISTS idx_messages_chat_created
    ON messages(chat_id, created_at ASC)
  `

  // Run additive migrations. ALTER TABLE throws if the column already exists,
  // so each migration is wrapped in try/catch — safe for repeated startups.
  runMigrations(db)

  return db
}

/**
 * Applies schema migrations that need to run after the initial CREATE TABLE
 * block. Using try/catch on each ALTER TABLE is idiomatic for SQLite — there's
 * no IF NOT EXISTS syntax for ADD COLUMN prior to SQLite 3.37.
 */
function runMigrations(db: DatabaseSync): void {
  try { db.exec('ALTER TABLE messages ADD COLUMN checklist TEXT') } catch { /* already exists */ }
}
